
# Module hruUI function

paramSamplingUI <- function(id) {

  # NS(id) returns a namespace function, which was save as `ns` and will
  # invoke later.
  
  ns <- NS(id)
  
  tagList(
    
    fluidRow(

      # -----------------------------------------------Parameter selection table
      column(width = 10,
             HTML("<b>","1. Select SWAT parameters to calibration and/or 
                  sensitivity analyis","</b>"),
      ),
      
      column(width = 10,
             checkboxInput('helpParameterSelection', 
                           'Display help for parameter selection', 
                           value = FALSE, width = NULL),
      ),
      
      column(width = 1,
             tippy("Help?", tooltip = "<span style='font-size:16px;'>
                   If you not sure about the parameter name, subbasin, land use, 
                   soil type, slope, check this box
                   <span>", 
                   allowHTML = TRUE, 
                   trigger = "click",
                   theme = "light"),
      ),
      
      conditionalPanel(
        condition = "input.helpParameterSelection == 1",
        column(width = 10,
               dataTableOutput('tableHelpParameterSelection'),
        ),
      ),
      
      column(width = 10,
             excelOutput("tableParaSelection", 
                         width = "100%", 
                         height = "1px"),
      ),
      
      column(width = 1,
             tippy("Help?", tooltip = "<span style='font-size:16px;'>
                   With hru-based parameters (e.g., parameters in
                   .hru files) you should fill in all fields of this table. 
                   With subbasin parameters, the land use, soil, slope can be left
                   empty. With basin parameters, the subbasin, landuse, soil, slope 
                   cells can be left emtpy. If you select all subbasins/landuse/soil
                   or slope, just type 'All'. Note: 'relative' change means 
                   x_new = x_old*(1 + appliedValue). 'absolute' change means
                   x_new = x_old + appliedValue. 'replace' means
                   x_new = appliedValue
                   <span>", 
                   allowHTML = TRUE, 
                   trigger = "click",
                   theme = "light"),
      ),
      

      column(width = 10,
             actionButton("checkParameterTableButton", 
                          "Click here to check the input table (IMPORTANT)",
                          #icon("paper-plane"), 
                          style="background-color: #87CEFA; 
                          border-color: #2e6da4"),
             verbatimTextOutput('checkParameterTableTxtOuput'),
      ),
      
      div( style = "margin-bottom: 10em",  
           column(width = 10,
           ),
      ),

      # ---------------------------------------------Parameter sampling approach
      column(width = 10,
             HTML("<b>",
                        "2. Parameter sampling",
                        "</b>"),
      ),
 
      column(width = 10,
             excelOutput("tableParaSampling", 
                         width = "100%", 
                         height = "1px"),
      ),
      
    
      column(width = 1,
             tippy("Help?", tooltip = "<span style='font-size:16px;'>
                   'Sensi' and 'Cali' mean for sensitivity and calibration 
                   simulations. The current of option is 'Sensi_Cali_(LHS)' means 
                   you can perform both sensitivity and calibration (SUIF2-like
                   approach) with parameter generated by uniform Latin Hypercube
                   Sampling (LHS).In this case, please insert <span style=
                   'color: red;'> the number of iteration
                   in the 'InputInfo' <span> . <span Other cases under development, DO NOT
                   TRY
                   <span>", 
                   allowHTML = TRUE, 
                   trigger = "click",
                   theme = "light"),
      ),
      
    )
    
  )}

